version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: mksolutions/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    depends_on:
      - "gui"
    volumes:
     - /openvpn/conf:/etc/openvpn
  gui:
    image: awalach/openvpn-web-ui
    container_name: openvpn-gui
    ports:
     - "8080:8080/tcp"
    restart: always
    volumes:
     - /openvpn/conf:/etc/openvpn
     - /openvpn/db:/opt/openvpn-gui/db
